"""Pack gbk_codec 0.4.0's MIT-licensed mapping without changing its entries."""
import ast
import base64
from pathlib import Path
import struct
import sys
import textwrap


def main():
    source = Path(sys.argv[1])
    text = source.read_text(encoding='utf-8')
    mapping = ast.literal_eval(
        text.split('json_gbk_to_char =', 1)[1].strip().removesuffix(';')
    )
    values = [0] * (126 * 190)
    for key, char in mapping.items():
        high, low = divmod(int(key, 16), 256)
        assert 0x81 <= high <= 0xfe and 0x40 <= low <= 0xfe and low != 0x7f
        index = (high - 0x81) * 190 + low - 0x40 - (low > 0x7f)
        values[index] = ord(char)
    assert sum(value != 0 for value in values) == len(mapping) == 21789
    packed = base64.b64encode(struct.pack('<23940H', *values)).decode('ascii')
    target = Path(__file__).resolve().parents[1] / 'lib/utils/src/gbk_table.dart'
    target.parent.mkdir(parents=True, exist_ok=True)
    content = (
        '// Generated by tool/generate_gbk_table.py from gbk_codec 0.4.0.\n'
        '// Copyright (c) 2021 John Wang. MIT; see gbk_table.LICENSE.\n'
        '// 126 lead bytes x 190 trail bytes; UTF-16LE, zero means unmapped.\n'
        'const gbkCodepointsBase64 =\n'
        + '\n'.join("    '" + part + "'" for part in textwrap.wrap(packed, 96))
        + ';\n'
    )
    target.write_text(content, encoding='utf-8', newline='\n')
    license_text = (source.parents[2] / 'LICENSE').read_text(encoding='utf-8')
    target.with_suffix('.LICENSE').write_text(license_text, encoding='utf-8')
    print(f'Packed {len(mapping)} mappings into {len(packed)} base64 bytes.')


if __name__ == '__main__':
    main()
